### DISCUSSION TITLE
Seemingly unable to get container/ldap service running

### DISCUSSION THREAD

**Discussion by blasphemite** [tiredofit/docker-openldap#46] [Q&A] [answered]
I seem to be totally unable to get the container fully functional, even when using the most basic adaptations to the example docker-compose file.

```
version: '2.4'
services:
    openldap:
        container_name: openldap
        hostname: ldap.example.lan
        ports:
            - 389:389
        volumes:
            - /etc/openldap/data:/var/lib/openldap
            - /etc/openldap/config:/etc/openldap/slapd.d
        environment:
            - DEBUG_MODE=FALSE
            - CONTAINER_NAME=openldap
            - HOSTNAME=ldap.example.lan
            - LOG_LEVEL=256
            - DOMAIN=example.lan
            - ADMIN_PASS=admin
            - CONFIG_PASS=config
            - ENABLE_READONLY_USER=FALSE
            - ENABLE_TLS=FALSE
            - TLS_VERIFY_CLIENT=never
            - SSL_HELPER_PREFIX=ldap
            - ENABLE_REPLICATION=FALSE
            - REMOVE_CONFIG_AFTER_SETUP=false
            - ENABLE_BACKUP=FALSE
            - CONTAINER_ENABLE_MONITORING=FALSE
        image: tiredofit/openldap
```

Which, when created, yields the following output:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 00-functions: applying...
[fix-attrs.d] 00-functions: exited 0.
[fix-attrs.d] 01-s6: applying...
[fix-attrs.d] 01-s6: exited 0.
[fix-attrs.d] 02-zabbix: applying...
[fix-attrs.d] 02-zabbix: exited 0.
[fix-attrs.d] 03-logrotate: applying...
[fix-attrs.d] 03-logrotate: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-startup: executing...
[cont-init.d] 00-startup: exited 0.
[cont-init.d] 01-timezone: executing...
[cont-init.d] 01-timezone: exited 0.
[cont-init.d] 02-permissions: executing...
[cont-init.d] 02-permissions: exited 0.
[cont-init.d] 03-monitoring: executing...
2021-09-06-00:26:58 [NOTICE] ** [monitoring] Disabling Monitoring Functionality
[cont-init.d] 03-monitoring: exited 0.
[cont-init.d] 04-scheduling: executing...
2021-09-06-00:26:58 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
[cont-init.d] 04-scheduling: exited 0.
[cont-init.d] 05-logging: executing...
2021-09-06-00:26:58 [NOTICE] ** [logging] Disabling Log Shipping Functionality
[cont-init.d] 05-logging: exited 0.
[cont-init.d] 06-messaging: executing...
2021-09-06-00:26:59 [NOTICE] ** [messaging] Container configured to route mail via SMTP to 'postfix-relay'
[cont-init.d] 06-messaging: exited 0.
[cont-init.d] 10-openldap: executing...
2021-09-06-00:26:59 [NOTICE] ** [openldap] Setting up directories
2021-09-06-00:26:59 [NOTICE] ** [openldap] Configuring OpenLDAP server
2021-09-06-00:26:59 [WARN] ** [openldap] First time install detected
2021-09-06-00:26:59 [NOTICE] ** [openldap] Using NIS schema type
2021-09-06-00:27:02 [NOTICE] ** [openldap] Converting schemas to LDIF
2021-09-06-00:27:02 [NOTICE] ** [openldap] Adding converted schemas
2021-09-06-00:27:02 [NOTICE] ** [openldap] Setting Security and ACLs
2021-09-06-00:27:02 [NOTICE] ** [openldap] Add bootstrap LDIFs
2021-09-06-00:27:03 [NOTICE] ** [openldap] Adding default top level data configuration
2021-09-06-00:27:03 [NOTICE] ** [openldap] Configuring LDAP client
2021-09-06-00:27:03 [NOTICE] ** [openldap] Configuring PPolicy check modules
[cont-init.d] 10-openldap: exited 0.
[cont-init.d] 99-container: executing...
[cont-init.d] 99-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-09-06-00:27:03 [STARTING] ** [scheduling] [1] Starting cron
```

No further console output after several minutes. Using `docker exec -it openldap netstat -tunlp` shows no service listening to ports 389 or 636. From what I can tell, nothing in the output gives clues to what is actually failing.

Full debug output: https://pastebin.com/phwXAdQA
