### ISSUE TITLE
Wrong OpenLDAP configuration for TLS

### ISSUE THREAD

**Issue by mjmucha** [tiredofit/docker-openldap#21]
Hey there!

I have a working ldap configuration (without TLS) and I'm now trying to add TLS authentication, which sadly doesn't work. After a bit of investigation i think i discovered a bug with the OpenLDAP initialization of this container.

Here is my docker-compose:
```
version: '3.7'

volumes:
  backup: {}
  data: {}
  config: {}

services:
  ldap:
    hostname: ldap.example.com
    image: tiredofit/openldap-fusiondirectory:latest
    container_name: ldap
    security_opt:
      - no-new-privileges:true
      - label:disable
    expose:
      - 389
      - 636
    volumes:
      - backup:/data/backup:rw,z
      - data:/var/lib/openldap:rw,z
      - config:/etc/openldap/slapd.d:rw,z
      - /etc/nginx/certs/ldap.tirion.org:/assets/slapd/certs:z
    environment:
      HOSTNAME: ldap.example.com
      BACKEND: mdb
      LOG_LEVEL: 256
      DOMAIN: example.com
      ADMIN_PASS_FILE: /run/secrets/LDAP_ADMIN_PASSWORD
      CONFIG_PASS_FILE: /run/secrets/LDAP_CONFIG_PASSWORD

      FUSIONDIRECTORY_ADMIN_USER: admin
      FUSIONDIRECTORY_ADMIN_PASS_FILE: /run/secrets/FD_ADMIN_PASSWORD
      ORGANIZATION: Example

      BASE_DN: "dc=example,dc=com"
      ENABLE_READONLY_USER: "TRUE"
      READONLY_USER_USER: readonly
      READONLY_USER_PASS_FILE: /run/secrets/LDAP_READONLY_USER_PASSWORD

      ENABLE_TLS: "TRUE"
      TLS_CRT_FILENAME: "cert.pem"
      TLS_KEY_FILENAME: "key.pem"
      TLS_CA_CRT_FILENAME: "fullchain.pem"
      TLS_ENFORCE: "FALSE"
      TLS_CIPHER_SUITE: SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC
      TLS_DH_PARAM_KEYSIZE: 4096
      TLS_VERIFY_CLIENT: try
      SSL_HELPER_PREFIX: ldap
      #TLS_RESET_PERMISSIONS: "FALSE"

      ENABLE_REPLICATION: "false"
      REMOVE_CONFIG_AFTER_SETUP: "false"

      ENABLE_ZABBIX: "FALSE"

      PLUGIN_ALIAS: "TRUE"
      PLUGIN_ARGONAUT: "FALSE"
      PLUGIN_AUDIT: "TRUE"
      PLUGIN_DSA: "FALSE"
      PLUGIN_LDAPDUMP: "TRUE"
      PLUGIN_LDAPMANAGER: "TRUE"
      PLUGIN_MAIL: "TRUE"
      PLUGIN_PERSONAL: "TRUE"
      PLUGIN_PPOLICY: "TRUE"
      PLUGIN_SSH: "TRUE"
      PLUGIN_SUDO: "FALSE"
      PLUGIN_SOGO: "FALSE"
      PLUGIN_SYSTEMS: "FALSE"
      PLUGIN_WEBSERVICE: FALSE"
      PLUGIN_GPG: "TRUE"

      BACKUP_CONFIG_CRON_PERIOD: 0 4 * * *
      BACKUP_DATA_CRON_PERIOD: 0 4 * * *
      BACKUP_TTL: 15

      LETSENCRYPT_HOST: ldap.example.com
      LETSENCRYPT_EMAIL: webmaster@example.com
    networks:
      - ldap
    restart: always
```
I'm using [Let's Encrypt](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion) for my certificates.

When I'm now trying to check the TLS authentication (just using portainer for this) it fails with the following untypical log entry: `TLS: could not load verify locations (file:"/assets/slapd/certs',dir:"')`. So it seem that OpenLDAP is looking for a file but only a path is given.

After looking into `/etc/openssl/ldap.conf` of my ldap container i noticed this line: `TLS_CACERT /assets/slapd/certs`. But after the [documentation of OpenLDAP](https://www.openldap.org/software//man.cgi?query=ldap.conf&sektion=5&apropos=0&manpath=OpenLDAP+2.4-Release), **`TLS_CACERT` should point to the file not the path**.

So i propose to change the line https://github.com/tiredofit/docker-openldap/blob/b80882c799bf13b99ed9c568d0481ef0de9d2fb7/install/etc/cont-init.d/10-openldap#L476 to 
`echo "TLS_CACERTDIR ${TLS_CA_CRT_PATH}" >> /etc/openldap/ldap.conf`
