### ISSUE TITLE
Waiting for OpenLDAP to be ready

### ISSUE THREAD

**Issue by siddjain** [tiredofit/docker-openldap#4]
tried this image and output is stuck at Waiting for OpenLDAP to be ready
```
$ docker logs -f jnj-ldap-server
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-run: applying... 
[fix-attrs.d] 01-run: exited 0.
[fix-attrs.d] 01-s6: applying... 
[fix-attrs.d] 01-s6: exited 0.
[fix-attrs.d] 02-zabbix: applying... 
[fix-attrs.d] 02-zabbix: exited 0.
[fix-attrs.d] 03-logrotate: applying... 
[fix-attrs.d] 03-logrotate: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-permissions: executing... 
[cont-init.d] 01-permissions: exited 0.
[cont-init.d] 02-zabbix: executing... 
[cont-init.d] 02-zabbix: exited 0.
[cont-init.d] 03-cron: executing... 
**** [cron] Enabling Cron
[cont-init.d] 03-cron: exited 0.
[cont-init.d] 04-smtp: executing... 
**** [smtp] Disabling SMTP Features
[cont-init.d] 04-smtp: exited 0.
[cont-init.d] 09-nginx: executing... 
[cont-init.d] 09-nginx: exited 0.
[cont-init.d] 10-openldap: executing... 
** [openldap] First time install detected
** [openldap] Using NIS schema type
** [openldap] Starting OpenLDAP Initialization Sequence
** [openldap] Waiting for OpenLDAP to be ready
```

**Comment by tiredofit** [comment]
Delete all folders and start fresh again but this time pass the environment variable `DEBUG_MODE=TRUE` and share the ouput?

**Comment by siddjain** [comment]
https://gist.github.com/siddjain/171660f4456d871235284163934f396a
5cc0aca6 @(#) $OpenLDAP: slapd 2.4.47 (Mar 29 2019 08:54:35) $
        @6c16896b5f57:/tiredofit/openldap:6.4/servers/slapd
        5cc0aca6 daemon: getaddrinfo() failed: Name does not resolve
        5cc0aca6 slapd stopped.
        5cc0aca6 connections_destroy: nothing to destroy.

[https://avatars1.githubusercontent.com/u/758321?s=400&v=4]<https://gist.github.com/siddjain/171660f4456d871235284163934f396a>

tiredofit-openlap-log.txt<https://gist.github.com/siddjain/171660f4456d871235284163934f396a>
GitHub Gist: instantly share code, notes, and snippets.
gist.github.com



________________________________

**Comment by tiredofit** [comment]
Thanks, there was another person having this issue recently. What it's hanging up on is not being able to resolve the dns name you have defined, so since it can't find it the whole system hangs. I'm trying to think on how I solved this on my own in the past - I will have to try a few tests on my end with bogus DNS as mine is routable at the moment. Are you using my exact docker-compose.yml example (with obvious changes to base_dn, passwords?

**Comment by tiredofit** [comment]
Update: I can confirm this happening. Easiest way in your docker-compose.yml right now is to change the following to:

hostname: localhost
domainname: localhost

and in environment variables:

HOSTNAME=localhost

If you have access to DNS obviously this would be better to use actual names, but this will get you up and running. I will update the docker-compose example for future users.

**Comment by nickadams675** [comment]
@tiredofit 
Apologies for commenting on a closed issue...

I am experiencing the same behavior with externally resolvable DNS to a publically reachable POC. I am able to start the example without issue. Thanks in advance for your assist!

<details><summary>Related Logs</summary>
openldap-app    | 5ceee165 @(#) $OpenLDAP: slapd 2.4.47 (May  2 2019 19:03:59) $
openldap-app    | 	@eeb43f157a45:/tiredofit/openldap:6.4/servers/slapd
openldap-app    | 5ceee165 daemon: bind(8) failed errno=2 (No such file or directory)
openldap-app    | 5ceee165 slapd stopped.
openldap-app    | 5ceee165 connections_destroy: nothing to destroy.
openldap-app    | + '[' '!' -e /run/openldap/slapd.pid ']'
openldap-app    | + sleep 0.1
openldap-app    | + '[' '!' -e /run/openldap/slapd.pid ']'
openldap-app    | + sleep 0.1
openldap-app    | + '[' '!' -e /run/openldap/slapd.pid ']'
openldap-app    | + sleep 0.1
openldap-app    | + '[' '!' -e /run/openldap/slapd.pid ']'
openldap-app    | + sleep 0.1
openldap-app    | + '[' '!' -e /run/openldap/slapd.pid ']'
</details>

Directory Listing
```bash
├── backup
├── certs
│   ├── cert.pem -> ../../nginx-certbot/data/certbot/conf/live/ldap.cpc.ctl.io/cert.pem
│   ├── chain.pem -> ../../nginx-certbot/data/certbot/conf/live/ldap.cpc.ctl.io/chain.pem
│   ├── fullchain.pem -> ../../nginx-certbot/data/certbot/conf/live/ldap.cpc.ctl.io/fullchain.pem
│   └── privkey.pem -> ../../nginx-certbot/data/certbot/conf/live/ldap.cpc.ctl.io/privkey.pem
├── config
│   ├── cn=config
│   │   ├── cn=module{0}.ldif
│   │   ├── cn=schema
│   │   │   ├── cn={0}core.ldif
│   │   │   ├── cn={1}cosine.ldif
│   │   │   ├── cn={2}inetorgperson.ldif
│   │   │   └── cn={3}nis.ldif
│   │   ├── cn=schema.ldif
│   │   ├── olcDatabase={0}config.ldif
│   │   ├── olcDatabase={-1}frontend.ldif
│   │   ├── olcDatabase={1}mdb.ldif
│   │   └── olcDatabase={2}monitor.ldif
│   └── cn=config.ldif
├── data
├── docker-compose.yml

```

<details><summary>And docker-compose</summary>
```yaml
version: '2'
services:
  openldap-app:
    hostname: ldap.cpc.ctl.io
    domainname: cpc.ctl.io
    container_name: openldap-app
    image: tiredofit/openldap
    ports:
      - 636:636
      - 389:389
    environment:
      - HOSTNAME=ldap.cpc.ctl.io
      - BACKEND=mdb
      - LOG_LEVEL=256
      - DOMAIN=cpc.ctl.io
      - ADMIN_PASS=admin
      - CONFIG_PASS=config
      - ENABLE_NGINX=false

      - BASE_DN=dc=cpc,dc=ctl,dc=io
      - ENABLE_READONLY_USER=false
      - READONLY_USER_USER=reader
      - READONLY_USER_PASS=reader

      - ENABLE_TLS=true
      - TLS_CRT_FILENAME=cert.pem
      - TLS_KEY_FILENAME=privkey.pem
      - TLS_CA_CRT_FILENAME=chain.pem
      - TLS_ENFORCE=false
      - TLS_CIPHER_SUITE=ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:-DHE-DSS:-RSA:!aNULL:!MD5:!DSS:!SHA
      - TLS_VERIFY_CLIENT=never
      - SSL_HELPER_PREFIX=ldap

      - ENABLE_REPLICATION=false
      - REMOVE_CONFIG_AFTER_SETUP=false
      - DEBUG_MODE=TRUE

      - BACKUP_CONFIG_CRON_PERIOD=0 4 * * *
      - BACKUP_DATA_CRON_PERIOD=0 4 * * *
      - BACKUP_TTL=15
    
      - ZABBIX_HOSTNAME=ldap.cpc.ctl.io
    volumes:
      - ./backup:/data/backup
      - ./data:/var/lib/openldap
      - ./config:/etc/openldap/slapd.d
      - ./certs:/assets/slapd/certs
    restart: always
```
</details>
